### ISSUE TITLE
Create your first PR by adding your github and linkedin link

### ISSUE THREAD

**Issue by anku580** [anku580/Starter-project-hacktoberfest#1]
Keep on adding your github and linkedin profile in the index.html file.

Please Star this repository by clicking the star button on top-right side of the screen.

## If you want to learn on how to resolve merge conflicts, you can watch this [youtube video](https://youtu.be/Mrh_YmPqNU8)

**Comment by mmuhamadamirzaidi** [comment]
Sure. Can I redesign the page as well @anku580 ?

**Comment by anku580** [comment]
@mmuhamadamirzaidi  Let me raise another issue for that. I will tag you.

**Comment by mmuhamadamirzaidi** [comment]
Sure. Thanks!

**Comment by anku580** [comment]
@mmuhamadamirzaidi Please refer to this issue https://github.com/anku580/Starter-project-hacktoberfest/issues/5

**Comment by romasinha** [comment]
@anku580 Can I add my LinkedIn and Github ID as well?

**Comment by mmuhamadamirzaidi** [comment]
> @mmuhamadamirzaidi Please refer to this issue #5

Done @anku580

**Comment by KeerthanaHK** [comment]
Hi, Can I add flex style?

**Comment by KeerthanaHK** [comment]
> Hi, Can I add flex style?

@anku580 I'm a beginner so please assign me this.

**Comment by anku580** [comment]
@KeerthanaHK sure you can add your contribution 💯

**Comment by Ayomal98** [comment]
Can i add a contribution too

**Comment by anushkarthik05** [comment]
Can I redesign the page and make it look attractive?
@anku580 I'm new to this. So kindly check my work

**Comment by anku580** [comment]
@Ayomal98 sure, please go ahead 👍

**Comment by anku580** [comment]
@anushkarthik05 please refer to this issue https://github.com/anku580/Starter-project-hacktoberfest/issues/5 for redesigning the index.html page.

**Comment by codeR49** [comment]
i want to give a shot @anku580

**Comment by anku580** [comment]
@codeR49 sure, please go ahead.

**Comment by mmuhamadamirzaidi** [comment]
Hi @anku580 @romasinha @KeerthanaHK @Ayomal98 @anushkarthik05 @codeR49 

Feels free to contribute to my repository also :D 

[https://github.com/mmuhamadamirzaidi/Hacktoberfest](https://github.com/mmuhamadamirzaidi/Hacktoberfest)

**Comment by ThejasreeKilari** [comment]
Hi I like to Contribute. I've added my LinkedIn and Github Id.

**Comment by kalpanaT-05** [comment]
Hello @anku580 can i contribute on this project?
