### ISSUE TITLE
Design the navbar as per HactoberFest 2020

### ISSUE THREAD

**Issue by anku580** [anku580/Starter-project-hacktoberfest#32]
Design the navbar so that it would have some theme related to hacktoberfest 2020.

![image](https://user-images.githubusercontent.com/25228101/94894340-c91aef80-04a6-11eb-9384-fe71d9af0fb3.png)

Also, make sure to follow me [here](https://github.com/anku580), I will follow you back. We can have a long discussion to contribute in open source.

## If you want to learn on how to resolve merge conflicts, you can watch this [youtube video](https://youtu.be/Mrh_YmPqNU8)

**Comment by infern018** [comment]
@anku580  can I work on this?

**Comment by anku580** [comment]
@infern018 sure, please go ahead :)

**Comment by hackgone** [comment]
I can make this. So shall i do it?? if not assigned

**Comment by anku580** [comment]
@hackgone sure please go ahead.

**Comment by hackgone** [comment]
can we use JS and bootstarp??

**Comment by anku580** [comment]
@hackgone , yes you can use it.

**Comment by Sutiksh** [comment]
Can I give it a try? I have't done web dev for a long time but want to practice so I don't forget it.

**Comment by anku580** [comment]
@Sutiksh please go ahead and try.
