### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by anku580** [anku580/Starter-project-hacktoberfest#33]
Update the README file with new labels and new look.

Also, make sure to follow me [here](https://github.com/anku580), I will follow you back. We can have a long discussion to contribute in open source.

**Comment by romasinha** [comment]
Hey @anku580 , can I take up this issue? I can make the README file accurate and presentable using appropriate labels

**Comment by anku580** [comment]
@romasinha Please go ahead :)

**Comment by anku580** [comment]
@romasinha Did not see your PR? Are you working on it? If you need any help please let me know.

**Comment by madhhuurrii** [comment]
Hii @anku580 I would like to add fork and clone images amd steps which would help first time contributors to work on the project locally

**Comment by anku580** [comment]
Hi @madhhuurrii , sure please start working on it.
