### ISSUE TITLE
Modify the UI for index.html page

### ISSUE THREAD

**Issue by anku580** [anku580/Starter-project-hacktoberfest#5]
You can add different sort of color combinations and add icons as required in the `index.html` page.

### Note - Please attach the screenshot while raising the PR

Also, make sure to follow me [here](https://github.com/anku580), I will follow you back. We can have a long discussion to contribute in open source.

**Comment by m4tr1k** [comment]
@anku580  Can I take this issue?

**Comment by anku580** [comment]
@m4tr1k yeah please go ahead 👍 

Thank you :)

**Comment by romasinha** [comment]
Hey @anku580 , please assign me this issue.

**Comment by mmuhamadamirzaidi** [comment]
Working on it @anku580

**Comment by mmuhamadamirzaidi** [comment]
Done @anku580

**Comment by anku580** [comment]
@romasinha sure, you can work on it as well

**Comment by anku580** [comment]
@mmuhamadamirzaidi Cool, will review your PR.

**Comment by mmuhamadamirzaidi** [comment]
> @mmuhamadamirzaidi Cool, will review your PR.

Thanks @anku580

**Comment by tanujajoshi1** [comment]
I want to work on it. Please let me

**Comment by anku580** [comment]
@tanujajoshi1 sure please go ahead 👍

**Comment by Ayomal98** [comment]
Can I work on it too

**Comment by anku580** [comment]
@Ayomal98 sure buddy :+1:

**Comment by Chauhan-Aniket** [comment]
I will modify UI without Bootstrap and Jquery and Navbar as you want :)

**Comment by saiharsha-22** [comment]
@anku580 I have added one new feature in the main website for Hacktober
Added dark mode feature for The Website #42

**Comment by saiharsha-22** [comment]
@anku580 I have modified the button you can check now
Added dark mode feature for The Website #42
